fieldLayouts:
  902cb6e1-33ee-4b4e-9696-3eadcee468a9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _cp/drafts
            type: craft\fieldlayoutelements\Template
            uid: ec6857b8-375f-4503-8c91-ac18df77235e
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fe253e4e-b6e6-4e47-964e-3d2aad9c35f2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e708fcd6-e624-4bca-803c-34ab069e72ed # Featured
            instructions: 'The article will stick to top on the home page and in the article index. Mark just one or two articles!'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af872e03-1253-4002-8d19-6dae768135a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7df417e8-1eea-46d8-85a7-2a20370a881e # Featured Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b64aa39-6335-4793-9938-c8fb7e109cbb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 087d6426-bc8d-4c44-b207-23dd11d11345 # Topics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7568e4b2-2c2c-49e0-b309-913d2b4224af
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 992f51d0-e22b-4c12-a6ba-d098fa334cd3 # Related Entries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbfcfd78-d08f-441c-8b8c-9ac8556e13b8
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
            instructions: null
            label: Content
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df0d7bce-2322-495f-8f41-5d7b87596331
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7df95195-2e58-4351-9695-13247cc8839d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            template: _cp/local-images
            type: craft\fieldlayoutelements\Template
            uid: c03ef924-c64d-4fb4-9509-0687e16b9cc6
            userCondition: null
            width: 100
          -
            elementCondition: null
            template: _cp/related-entries
            type: craft\fieldlayoutelements\Template
            uid: 9cc0a276-a1cf-4c5e-953c-020e72a6d5be
            userCondition: null
            width: 100
        name: Info
        uid: 33ee5cf5-2545-423b-8fa2-e4ae0608171a
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 7a045fb7-ed74-4c72-8482-fc700ab663ca # Article
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: language
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
