fieldLayouts:
  05f6e9e5-cdf4-475d-b201-37ceb84cda7b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dbf670cc-fda4-4f42-b57e-903835009aea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7df417e8-1eea-46d8-85a7-2a20370a881e # Featured Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 614ce36d-f602-4fbb-b691-1172e5a7b503
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 30cfb989-f158-4630-9bde-19f468e9519c # Wide Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1be82713-a59c-499a-83b6-f3bfcb21c646
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d286f9ed-4b17-45c9-9964-987f2ee7e692
        userCondition: null
handle: topicsIndex
hasTitleField: true
name: 'Topics Index'
section: 84b98802-2548-4aed-b67e-fc97f6ed9e30 # Page
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: language
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
