columnSuffix: null
contentColumnType: string
fieldGroup: bd76fb6e-8765-41d3-8e8a-02e37e127c80 # Common
handle: featuredImageBySite
instructions: null
name: 'Featured Image By Site'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  defaultUploadLocationSubpath: featured
  localizeRelations: true
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\assets\WidthConditionRule
              -
                - uid
                - 33b76784-dbe1-4c37-ad04-1ce6cc49e336
              -
                - operator
                - '>='
              -
                - value
                - '800'
              -
                - maxValue
                - ''
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
