columnSuffix: null
contentColumnType: string
fieldGroup: bd76fb6e-8765-41d3-8e8a-02e37e127c80 # Common
handle: relatedEntries
instructions: null
name: 'Related Entries'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
    - 'section:7a045fb7-ed74-4c72-8482-fc700ab663ca' # Article
    - 'section:599c71b9-f295-4a4d-b1c3-7792f4da3dd6' # Topic
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
